// Generated by CoffeeScript 1.6.3
(function() {
  var setCurrentAge;

  setCurrentAge = function() {
    var age, birthDate, icon, m, today;
    today = new Date();
    birthDate = new Date(1991, 6, 4);
    age = today.getFullYear() - birthDate.getFullYear();
    m = today.getMonth() - birthDate.getMonth();
    if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
      age--;
    }
    $('.js-age').text(age);
    if (today.getDate() === birthDate.getDate() && today.getMonth() === birthDate.getMonth()) {
      icon = $(document.createElement('i'));
      icon.addClass('icon-gift birthday').attr('data-toggle', 'tooltip').attr('title', "C\'est mon anniversaire aujourd\'hui !").text(' ');
      $('.js-age').prepend(icon);
      return icon.tooltip();
    }
  };

  $(function() {
    setCurrentAge();
    $('.toggle-expend').click(function() {
      return $('body').toggleClass('expended');
    });
    $('*[data-scroll]').each(function() {
      var xPos,
        _this = this;
      xPos = $(this).css('backgroundPosition').split(' ')[0];
      return $(window).scroll(function() {
        var yPos;
        yPos = $(window).scrollTop() / $(_this).data('scroll');
        return $(_this).css('backgroundPosition', "" + xPos + " " + yPos + "px");
      });
    });
    $('a[data-preview]').each(function() {
      var root;
      root = $('.xp');
      return $(this).click(function(e) {
        var futurVisibleElem, height, previewNum, visibleElem;
        e.preventDefault();
        height = root.find('.thumbnails-wrapper').height();
        previewNum = $(this).data('preview');
        root.find('.details').removeClass('detail-1 detail-2 detail-3 detail-4').addClass("detail-" + previewNum).css('height', height);
        visibleElem = $('.js-visible');
        futurVisibleElem = root.find(".detail[data-detail=" + previewNum + "]");
        if (!visibleElem.is(futurVisibleElem)) {
          visibleElem.fadeOut('slow').removeClass('js-visible');
          return futurVisibleElem.addClass('js-visible').fadeIn('slow');
        }
      });
    });
    return $('.js-first-showed').click();
  });

}).call(this);
